import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* header */}

      <Header />

      {/* header */}

      {/* nav */}

      <Nav />

      {/* nav */}

      {/* result */}
      {/* result */}
    </div>
  )
}
